
version: '3.9'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./src:/home/node/app/src
    container_name: ts-node-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start:dev